### ISSUE TITLE
Sloppy No-Data Handling in Report

### ISSUE THREAD

**Issue by ergonlogic** [ginkgostreet/civicrm-metrics-server#5]
There appears to be a bug on the report page when no data is present:

> Notice: Undefined offset: 0 in CRM_Metricserver_Page_Report->run() (line 42 of .../civicrm/extensions/civicrm-metrics-server/CRM/Metricserver/Page/Report.php).
> Warning: array_keys() expects parameter 1 to be array, null given in CRM_Metricserver_Page_Report->run() (line 42 of .../civicrm/extensions/civicrm-metrics-server/CRM/Metricserver/Page/Report.php).

**Comment by caracolmzd** [comment]
@ergonlogic Thanks for reporting this. I changed the issue description because it isn't technically an error.
Notices and Warnings should not be displayed on production sites. The array being null is not a failure and will only occur if the civicrm_metrics_server database table is empty.
